### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by rebaz36** [limavfabio/todo-list#4]
# [Morning session: Peer-to-peer code review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/morning-peer-to-peer-reviews.md)

**Comment by rebaz36** [comment]
# great job so far @limavfabio, note the followings to improvise

- add some colors for better visualization
- hovers and focus effects could help you give a better user experience 
- missing refresh button

**Comment by dgsierra** [comment]
Great Work!
![image](https://user-images.githubusercontent.com/62531899/184380360-65504cd4-1846-4746-b3be-034814853b78.png)

[Optional]
It would be great to have a icon for Add you can do it using Font Awesome:
Import:
`<script src="https://kit.fontawesome.com/841b60bdd5.js" crossorigin="anonymous"></script>`

and for the plus sing:
`<i class="fa-solid fa-plus"></i>`
